version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: python3 app.py
workflows:
  build_test:
    jobs:
      - run_test
      - build:
         requires: 
          - run_test